@url = http://localhost:62116/api/todos
@id = 7132333e-9492-4418-a933-368f5ba0334c

DELETE {{url}}/{{id}} HTTP/1.1
content-type: application/json

{
    "title": "Shopping",
    "description": "Buy a cookies and apple pie"
}
